### ISSUE TITLE
Consider using issue tracker + milestones + tags for project management

### ISSUE THREAD

**Issue by paluh** [Kamirus/purescript-selda#3]
I think that current development model doesn't scale well and can be confusing for new contributors. I think that `selda` is starting to be useful in its current shape and we can start to release it.
I understand that there is still a lot of moving parts, but we have to decide on some core and plan all design experiments according to it.
I propose turning TODOs into issues and tagging them and also introducing milestones with clear goals for the lib.

**Comment by paluh** [comment]
P.S.
@Kamirus Of course I'm really happy to help with this after my holiday (in the second half of August ;-))

**Comment by Kamirus** [comment]
I'm looking forward to it :)

**Comment by JordanMartinez** [comment]
Isn't this as simple as creating an issue for each item in `todo.md`?

**Comment by paluh** [comment]
> Isn't this as simple as creating an issue for each item in todo.md?

Yeah. Plus (possibly) merging `experimental` branch, making a release and tagging some milestones on these TODOS.  ;-)

**Comment by JordanMartinez** [comment]
I started opening issues for the todo.md file, but then wondered how much of it is still accurate. Some are cryptic, so I'm not entirely sure what the issue even is:
```
## TODO
- check:
  - insert_ T [{ id: 1...}]; insert_ T [{ ... }] 2nd without id; key exists!
  - table name: public.Table, alias without public...
  - literal in group by - runtime error
  - add additional phantom type for Col to indicate OR change Expr to polymorphic variant
- explicit having
- typeclass for record validation - better type errors
- more tests
- more restrict operators
- add restrictions to operators (Ord? Eq?)
- IN / NOT IN
- order by
- limit
- default, sequenced primary key - do not insert those, but do select
- error handling
- delete and update with RETURNING
- pgclient stable version
- notNull (:: Maybe a -> a)
- print query, query to string

## Known issues
- max on empty set returns null (workaround: avoid aggregations with group by () on empty tables)
- orderBy in a query without groupBy (also orderBy max sth that is not in the group by)
- groupBy not a column, results in runtime error
- nested records not working - generic part - pure $ { r1: { a, b }, r2: { c }, d }
```

**Comment by Kamirus** [comment]
Thanks, I've opened the rest of the relevant in the `todo.md`. I've left some in the file because I think it will better to add them later. If you think otherwise feel free to add them :)

**Comment by JordanMartinez** [comment]
Thanks. That helps clarify things.

**Comment by paluh** [comment]
> I've left some in the file because I think it will better to add them later.

I don't think it is a good idea. If it is your internal / informal plan which you don't want to share just remove it from repository for clarity - that's just my suggestion :-P
Consistent development approach will simplify users and our life as issues (even closed) are easily searchable and everybody can see what is or was on our development radar etc.

**Comment by paluh** [comment]
P.S. Of course I don't want to multiply issues with some unrealistic or "nice to have" issues too ;-)
