### ISSUE TITLE
Provide a way to specify required, optional and forbidden columns for `insert` and `update`

### ISSUE THREAD

**Issue by paluh** [Kamirus/purescript-selda#4]
As @JordanMartinez pointed out on the slack channel there is a problem with `INSERT` operation. Currently `insert` requires you to provide values for all columns of a given table. This defeats the purpose of defaults or auto columns on the db side. Short example and current "solution" described by Jordan can be found here:

https://gist.github.com/JordanMartinez/c5ad7334281f21863cf22cbfb70f0372#file-seldaexample-purs-L42-L65

I propose adding something like this (modulo naming) for this purpose:

https://github.com/paluh/purescript-little-selda/blob/master/src/Database/Selda/Little.purs#L499

This allows user to specify three options for a given column:

• DB takes care entirely for a given column and it is forbidden to specify its value in `insert` or `update`,
• DB provides default value but allows you to override it during `insert`. In such a case you have to wrap value in a `Maybe` in `insert` or `update` statements,
• DB doesn't provide anything for given column so `insert` / `update` requires you to provide a value.

I hope that we add something even better to the lib finally. 

Unwrapped column type in a table declaration should be translated to `NoDbDefault`.

**Comment by Kamirus** [comment]
Added `Auto` and `Default` constraints that can be used in a table definition.

```purescript
-- an example of a table definition that uses `Auto` and `Default` constraints 
employees ∷ Table ( id ∷ Auto Int, name ∷ String, salary ∷ Default Int )
employees = Table { name: "employees" }
```

This change impacts the insert operations. Now it is not allowed to insert columns with `Auto` constraint and it is optional to provide `Default` columns.

```purescript
insert_ employees [{ name: "E2" }]
insert_ employees [{ name: "E1", salary: 123 }]
insert_ employees [{ id: 1, name: "E1", salary: 123 }] -- type error, id is Auto, so it cannot be inserted
```

**Comment by JordanMartinez** [comment]
Just wanted to say thanks for implementing this. I've begun working on a small website using Hyper and this library. I'm focusing on other things but this small change reduced a number of lines of boilerplate due to having to use the solution I specified in the opening comment.

**Comment by Kamirus** [comment]
Glad to hear :)
