### ISSUE TITLE
Update to be compatible on v0.14.1 PS release

### ISSUE THREAD

**Issue by JordanMartinez** [Kamirus/purescript-selda#56]
Any interest on getting this updated to v0.14.1?

**Comment by paluh** [comment]
Yeah, sure - we want to do this. I know that @Kamirus Kamirus is waiting for some updates from my side. I'm still working on 0.13.8 so I'm not able to look into [postgresql update](https://github.com/rightfold/purescript-postgresql-client/pull/56) which should be merged but alongside _pool-query_ branch and a proper release. There are other deps which are still not ready for 0.14.1 like polyform which is a testing dependency.
Sorry for this delay :-(

**Comment by JordanMartinez** [comment]
I've submitted a PR to polyform that updates it to v0.14.1. I'll do the same for the batteries libs.
